export const styles = `
  :root{color-scheme:dark;--bg-start:#08111f;--bg-end:#0b1220;--text:#e2e8f0;--muted:#94a3b8;--line:#33415566;--panel:#0f172acc;--panel-soft:#0f172a88;--panel-strong:#0f172af2;--button:#0f172a;--button-active:#172554;--brand:#60a5fa;--brand2:#22d3ee;--danger:#fb7185;--ok:#34d399;font-family:Inter,system-ui,sans-serif}
  :root[data-theme="light"]{color-scheme:light;--bg-start:#eef4ff;--bg-end:#f8fbff;--text:#0f172a;--muted:#64748b;--line:#cbd5e1;--panel:#ffffffd9;--panel-soft:#ffffff;--panel-strong:#f8fafc;--button:#f8fafc;--button-active:#dbeafe;--brand:#2563eb;--brand2:#0ea5e9;--danger:#e11d48;--ok:#059669}
  *{box-sizing:border-box}
  html,body{min-height:100%}
  body{margin:0;background:linear-gradient(180deg,var(--bg-start),var(--bg-end));color:var(--text);transition:background .25s ease,color .25s ease}
  a{text-decoration:none;color:inherit}button,input,select{font:inherit}
  .page{width:min(1240px,calc(100% - 28px));margin:22px auto}
  .hero,.card{background:var(--panel);border:1px solid var(--line);border-radius:20px;backdrop-filter:blur(12px);box-shadow:0 8px 30px #0206171f;transition:background .2s ease,border-color .2s ease,box-shadow .2s ease}
  .hero{display:flex;justify-content:space-between;gap:16px;padding:22px}.hero h1{margin:0;font-size:28px}.hero p{margin:8px 0 0;color:var(--muted)}
  .grid{display:grid;grid-template-columns:2fr 1fr;gap:16px;margin-top:16px}.card-head,.card-body{padding:18px}.card-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}
  .toolbar,.actions,.crumbs,.row-actions{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.crumbs button{border:none;background:none;color:var(--muted);padding:0;cursor:pointer}
  .btn,.pick{display:inline-flex;align-items:center;justify-content:center;min-height:38px;padding:0 14px;border-radius:12px;border:1px solid var(--line);background:var(--button);color:var(--text);cursor:pointer;transition:all .18s ease}
  .btn:hover,.pick:hover{transform:translateY(-1px);border-color:color-mix(in srgb,var(--brand) 40%,var(--line));box-shadow:0 6px 18px #0f172a1a}
  .btn:active,.pick:active{transform:translateY(0)}
  .btn.primary,.pick.primary{background:linear-gradient(135deg,var(--brand),var(--brand2));border-color:transparent;color:#fff}
  .btn.danger{border-color:color-mix(in srgb,var(--danger) 50%,var(--line));color:color-mix(in srgb,var(--danger) 78%,#fff)}
  .btn.small{min-height:32px;padding:0 10px;font-size:13px}.pick input{display:none}
  .btn.active{border-color:color-mix(in srgb,var(--brand) 60%,var(--line));background:var(--button-active)}
  .badge{display:inline-flex;padding:8px 12px;border-radius:999px;border:1px solid color-mix(in srgb,var(--ok) 55%,var(--line));background:color-mix(in srgb,var(--ok) 20%,transparent);color:color-mix(in srgb,var(--ok) 75%,#ffffff);font-size:13px}
  .drop{margin:0 18px 18px;padding:14px;border:1px dashed color-mix(in srgb,var(--brand) 55%,var(--line));border-radius:14px;color:var(--muted)}.drop.active{background:color-mix(in srgb,var(--brand2) 18%,transparent);color:var(--text)}
  .status{min-height:22px;color:var(--muted);margin-bottom:12px}.status.error{color:#ef4444}.status.success{color:#10b981}.muted{color:var(--muted)}.mono{font-family:ui-monospace,Consolas,monospace}
  .table{overflow:auto;border:1px solid var(--line);border-radius:16px}table{width:100%;border-collapse:collapse;table-layout:fixed}th,td{padding:13px 14px;text-align:left;border-bottom:1px solid color-mix(in srgb,var(--line) 65%,transparent);white-space:nowrap;font-size:14px;vertical-align:middle;min-width:0}th{position:sticky;top:0;background:var(--panel-strong);color:var(--muted)}tr:last-child td{border-bottom:none}tr.row:hover td{background:color-mix(in srgb,var(--brand) 9%,transparent)}.name{min-width:0;max-width:0}.name-text{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.row{cursor:pointer}
  .cards{display:grid;grid-template-columns:repeat(auto-fill,minmax(140px,1fr));gap:12px}.card-item{padding:14px;border:1px solid var(--line);border-radius:16px;background:var(--panel-soft);display:grid;gap:10px;min-height:160px;min-width:0;transition:transform .16s ease,border-color .16s ease,box-shadow .16s ease}.card-item:hover{transform:translateY(-1px);border-color:color-mix(in srgb,var(--brand) 35%,var(--line));box-shadow:0 8px 18px #0f172a1a}.card-item-top{display:flex;justify-content:space-between;align-items:flex-start;gap:8px}.card-icon{font-size:42px;line-height:1}.card-name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:14px;min-width:0}.card-meta{display:grid;gap:4px;color:var(--muted);font-size:12px}.hidden{display:none !important}
  .stats{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.stat,.info{padding:14px;border:1px solid var(--line);border-radius:14px;background:var(--panel-soft)}.stat strong{display:block;margin-top:6px;font-size:22px}.stack{display:grid;gap:10px}
  .share-list{display:grid;gap:10px;max-height:240px;overflow:auto}.share-item{padding:12px;border:1px solid var(--line);border-radius:12px;background:var(--panel-soft)}.share-item-head{display:flex;justify-content:space-between;gap:10px;align-items:center}.share-meta{display:grid;gap:6px;margin-top:8px;color:var(--muted);font-size:13px}.task-list{display:grid;gap:10px;max-height:320px;overflow:auto;margin-top:12px}.task-item{padding:12px;border:1px solid var(--line);border-radius:12px;background:var(--panel-soft);display:grid;gap:8px;min-width:0;transition:border-color .16s ease}.task-item:hover{border-color:color-mix(in srgb,var(--brand) 35%,var(--line))}.task-item-head{display:flex;justify-content:space-between;gap:10px;align-items:flex-start;min-width:0}.task-title-btn{display:block;min-width:0;max-width:100%;padding:0;border:none;background:none;color:inherit;text-align:left;cursor:pointer}.task-title-btn:hover .task-title{text-decoration:underline;text-decoration-color:color-mix(in srgb,var(--brand) 70%,transparent)}.task-title{display:block;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.task-badge{display:inline-flex;padding:4px 10px;border-radius:999px;border:1px solid var(--line);font-size:12px;white-space:nowrap;flex-shrink:0}.task-badge.queued{color:#f59e0b;background:#f59e0b22;border-color:#f59e0b55}.task-badge.running{color:#3b82f6;background:#3b82f622;border-color:#3b82f655}.task-badge.success{color:#10b981;background:#10b98122;border-color:#10b98155}.task-badge.error{color:#ef4444;background:#ef444422;border-color:#ef444455}.task-meta{display:grid;gap:4px;color:var(--muted);font-size:13px;min-width:0}.task-meta div{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.task-error{color:#ef4444;word-break:break-word;overflow-wrap:anywhere}
  dialog{width:min(640px,calc(100vw - 24px));border:1px solid var(--line);border-radius:18px;padding:0;background:var(--panel);color:var(--text)}dialog::backdrop{background:#02061766}.modal-head,.modal-body{padding:18px}.modal-head{border-bottom:1px solid var(--line)}.modal-head h2{margin:0}.input,.select{width:100%;min-height:42px;padding:0 12px;border-radius:12px;border:1px solid var(--line);background:var(--button);color:var(--text)}
  .form-grid{display:grid;grid-template-columns:1fr 180px;gap:10px}.empty{padding:22px;text-align:center;color:var(--muted)}
  .player-container{margin-bottom:16px}.player-container video{width:100%;max-height:70vh;border-radius:12px;background:#000}.audio-player{display:flex;flex-direction:column;align-items:center;gap:16px;padding:24px 0}.audio-icon{font-size:64px;line-height:1}.audio-player audio{width:100%}
  @media (max-width:960px){.grid{grid-template-columns:1fr}.hero{flex-direction:column}.form-grid{grid-template-columns:1fr}}
`;

export function safe(value: string): string {
  return value.replace(/</g, "\u003c").replace(/>/g, "\u003e").replace(/&/g, "\u0026");
}
