// @ts-nocheck
export {}

const root=document.getElementById('share-page');if(!root)throw new Error('share page root missing');const state={code:root.dataset.shareCode||'',sub:'',selected:new Set(),mode:'folder'};
    const e={crumbs:document.getElementById('crumbs'),refresh:document.getElementById('refresh'),downloadSelected:document.getElementById('downloadSelected'),status:document.getElementById('status'),summary:document.getElementById('summary'),rows:document.getElementById('rows')};
    const esc=(v)=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
    const bytes=(n)=>{if(n==null)return '-';const u=['B','KB','MB','GB','TB'];let v=Number(n),i=0;while(v>=1024&&i<u.length-1){v/=1024;i++}return v.toFixed(v>=100||i===0?0:1)+' '+u[i]};
    const time=(v)=>v?new Date(v).toLocaleString('zh-CN',{hour12:false}):'-';
    const trimSlash=(value)=>{const input=String(value||'');return input.endsWith('/')?input.slice(0,-1):input};
    const setStatus=(t,k='')=>{e.status.textContent=t;e.status.className=k?'status '+k:'status'};
    const api=async(url)=>{const r=await fetch(url);const c=r.headers.get('content-type')||'';const d=c.includes('application/json')?await r.json():await r.text();if(!r.ok)throw new Error(typeof d==='string'?d:(d.error||r.statusText));return d};
    const sharedUrl=(path,download)=>path?('/s/'+state.code+'/file?path='+encodeURIComponent(path)+(download?'&download=1':'')):('/s/'+state.code+'/file'+(download?'?download=1':''));
    function updatePick(){e.downloadSelected.disabled=state.mode!=='folder'||state.selected.size===0}
    function crumbsRender(){e.crumbs.innerHTML='';const root=document.createElement('button');root.textContent='分享根目录';root.onclick=()=>load('');e.crumbs.appendChild(root);const plain=trimSlash(state.sub);const parts=plain?plain.split('/'):[];let current='';for(const part of parts){const sep=document.createElement('span');sep.textContent='/';e.crumbs.appendChild(sep);current+=part+'/';const btn=document.createElement('button');btn.textContent=part;const target=current;btn.onclick=()=>load(target);e.crumbs.appendChild(btn)}}
    function summaryRender(data){const list=[['类型',data.kind==='file'?'文件分享':'文件夹分享'],['原始路径',data.rootPath],['当前目录',data.currentPrefix||data.rootPath],['创建时间',time(data.createdAt)],['过期时间',data.expiresAt?time(data.expiresAt):'永久有效'],['项目数量',String((data.folders?.length||0)+(data.files?.length||0)||1)]];e.summary.innerHTML=list.map((item)=>'<div class="info"><div class="muted">'+esc(item[0])+'</div><div class="mono">'+esc(String(item[1]))+'</div></div>').join('')}
    function rowsRender(data){state.selected.clear();updatePick();if(data.kind==='file'){state.mode='file';e.rows.innerHTML='<tr><td></td><td class="name">📄 '+esc(data.file.name)+'</td><td>文件</td><td>'+bytes(data.file.size)+'</td><td>'+esc(time(data.file.uploaded))+'</td><td><div class="actions"><a class="btn" href="'+sharedUrl('',false)+'" target="_blank" rel="noopener">在线打开</a><a class="btn primary" href="'+sharedUrl('',true)+'">下载</a></div></td></tr>';return}state.mode='folder';if(!data.folders.length&&!data.files.length){e.rows.innerHTML='<tr><td colspan="6" class="empty">这个分享目录当前没有可展示的文件。</td></tr>';return}const html=[];for(const folder of data.folders){html.push('<tr class="row" data-folder="'+esc(folder.subpath)+'"><td></td><td class="name">📁 '+esc(folder.name)+'</td><td>文件夹</td><td>-</td><td>-</td><td class="muted">点击进入</td></tr>')}for(const file of data.files){html.push('<tr data-file="'+esc(file.subpath)+'"><td><input type="checkbox" data-pick="'+esc(file.subpath)+'" /></td><td class="name">📄 '+esc(file.name)+'</td><td>文件</td><td>'+bytes(file.size)+'</td><td>'+esc(time(file.uploaded))+'</td><td><div class="actions"><a class="btn" href="'+sharedUrl(file.subpath,false)+'" target="_blank" rel="noopener">在线打开</a><a class="btn primary" href="'+sharedUrl(file.subpath,true)+'">下载</a></div></td></tr>')}e.rows.innerHTML=html.join('');for(const row of e.rows.querySelectorAll('tr[data-folder]')){row.onclick=()=>load(row.dataset.folder)}for(const box of e.rows.querySelectorAll('input[data-pick]')){box.addEventListener('change',()=>{const v=box.dataset.pick;if(!v)return;if(box.checked)state.selected.add(v);else state.selected.delete(v);updatePick()})}}
    async function load(sub=state.sub){state.sub=sub;crumbsRender();setStatus('正在加载分享内容…');try{const data=await api('/share-api/'+state.code+'?sub='+encodeURIComponent(sub));summaryRender(data);rowsRender(data);setStatus('分享内容已更新','success')}catch(err){setStatus(err.message||'分享加载失败','error')}}
    e.refresh.onclick=()=>load(state.sub);e.downloadSelected.onclick=()=>{for(const path of state.selected){window.open(sharedUrl(path,true),'_blank','noopener')}};load('');
