type DashboardOptions = { appName: string };
type ShareOptions = { appName: string; shareCode: string };

const styles = `
  :root{color-scheme:dark;--line:#33415566;--text:#e2e8f0;--muted:#94a3b8;--brand:#60a5fa;--brand2:#22d3ee;font-family:Inter,system-ui,sans-serif}
  *{box-sizing:border-box}body{margin:0;background:linear-gradient(180deg,#08111f,#0b1220);color:var(--text)}a{text-decoration:none;color:inherit}button,input{font:inherit}
  .page{width:min(1200px,calc(100% - 28px));margin:22px auto}.hero,.card{background:#0f172acc;border:1px solid var(--line);border-radius:20px;backdrop-filter:blur(12px)}
  .hero{display:flex;justify-content:space-between;gap:16px;padding:22px}.hero h1{margin:0;font-size:28px}.hero p{margin:8px 0 0;color:var(--muted)}
  .grid{display:grid;grid-template-columns:2fr 1fr;gap:16px;margin-top:16px}.card-head,.card-body{padding:18px}.card-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}
  .toolbar,.actions,.crumbs{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.crumbs button{border:none;background:none;color:var(--muted);padding:0;cursor:pointer}
  .btn,.pick{display:inline-flex;align-items:center;justify-content:center;min-height:38px;padding:0 14px;border-radius:12px;border:1px solid var(--line);background:#0f172a;color:var(--text);cursor:pointer}
  .btn.primary,.pick.primary{background:linear-gradient(135deg,var(--brand),var(--brand2));border-color:transparent;color:#fff}.pick input{display:none}
  .badge{display:inline-flex;padding:8px 12px;border-radius:999px;border:1px solid #22c55e55;background:#16a34a22;color:#bbf7d0;font-size:13px}
  .drop{margin:0 18px 18px;padding:14px;border:1px dashed #60a5fa66;border-radius:14px;color:var(--muted)}.drop.active{background:#0891b233;color:#cffafe}
  .status{min-height:22px;color:var(--muted);margin-bottom:12px}.status.error{color:#fecaca}.status.success{color:#bbf7d0}.muted{color:var(--muted)}.mono{font-family:ui-monospace,Consolas,monospace}
  .table{overflow:auto;border:1px solid var(--line);border-radius:16px}table{width:100%;border-collapse:collapse}th,td{padding:13px 14px;text-align:left;border-bottom:1px solid #33415533;white-space:nowrap;font-size:14px}th{position:sticky;top:0;background:#0f172af2;color:var(--muted)}tr:last-child td{border-bottom:none}.name{min-width:260px}.row{cursor:pointer}
  .stats{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.stat,.info{padding:14px;border:1px solid var(--line);border-radius:14px;background:#0f172a88}.stat strong{display:block;margin-top:6px;font-size:22px}.stack{display:grid;gap:10px}
  dialog{width:min(560px,calc(100vw - 24px));border:1px solid var(--line);border-radius:18px;padding:0;background:#08111ff7;color:var(--text)}dialog::backdrop{background:#020617aa}.modal-head,.modal-body{padding:18px}.modal-head{border-bottom:1px solid var(--line)}.modal-head h2{margin:0}.input{width:100%;min-height:42px;padding:0 12px;border-radius:12px;border:1px solid var(--line);background:#0f172a;color:var(--text)}
  @media (max-width:960px){.grid{grid-template-columns:1fr}.hero{flex-direction:column}}
`;

function safe(value: string): string {
  return value.replace(/</g, "\\u003c").replace(/>/g, "\\u003e").replace(/&/g, "\\u0026");
}

export function renderDashboardHtml(options: DashboardOptions): string {
  const appName = safe(options.appName);
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1" /><title>${appName}</title><style>${styles}</style></head><body>
  <div class="page">
    <section class="hero"><div><h1>${appName}</h1><p>个人轻网盘：上传、浏览、查看详情、生成公开短链分享。</p></div><div class="actions"><span class="badge" id="who">正在验证身份…</span><button class="btn" id="refresh">刷新</button></div></section>
    <div class="grid">
      <section class="card">
        <div class="card-head"><div><div class="muted">当前目录</div><div class="crumbs" id="crumbs"></div></div><div class="toolbar"><label class="pick primary">上传文件<input id="pickFiles" type="file" multiple /></label><label class="pick">上传文件夹<input id="pickFolder" type="file" multiple webkitdirectory directory /></label></div></div>
        <div class="drop" id="dropzone">拖拽文件或文件夹到这里，自动上传到当前目录。</div>
        <div class="card-body"><div class="status" id="status"></div><div class="table"><table><thead><tr><th>名称</th><th>类型</th><th>大小</th><th>更新时间</th><th>MIME</th><th>操作</th></tr></thead><tbody id="rows"></tbody></table></div></div>
      </section>
      <aside class="card"><div class="card-head"><div><div class="muted">概览</div><h2 style="margin:6px 0 0;font-size:22px">R2 目录面板</h2></div></div><div class="card-body stack"><div class="stats"><div class="stat"><div class="muted">文件夹</div><strong id="folderCount">0</strong></div><div class="stat"><div class="muted">文件</div><strong id="fileCount">0</strong></div></div><div class="info"><div class="muted">当前路径</div><div class="mono" id="pathView">/</div></div><div class="info">右键任意行可快速生成分享短链。</div><div class="info">文件支持详情、在线打开、下载；文件夹支持进入与分享。</div></div></aside>
    </div>
  </div>
  <dialog id="detailDialog"><div class="modal-head"><h2>对象信息</h2></div><div class="modal-body"><div class="stack" id="detailBody"></div><div class="actions"><button class="btn" id="openFile">在线打开</button><button class="btn primary" id="downloadFile">下载</button><button class="btn" id="closeDetail">关闭</button></div></div></dialog>
  <dialog id="shareDialog"><div class="modal-head"><h2>分享短链</h2></div><div class="modal-body"><div class="info mono" id="shareTarget"></div><input class="input mono" id="shareLink" readonly /><div class="actions"><button class="btn primary" id="createShare">生成短链</button><button class="btn" id="copyShare">复制</button><button class="btn" id="closeShare">关闭</button></div></div></dialog>
  <script>
    const state={prefix:'',session:null,detail:null,share:null};
    const e={who:document.getElementById('who'),refresh:document.getElementById('refresh'),crumbs:document.getElementById('crumbs'),rows:document.getElementById('rows'),status:document.getElementById('status'),folderCount:document.getElementById('folderCount'),fileCount:document.getElementById('fileCount'),pathView:document.getElementById('pathView'),pickFiles:document.getElementById('pickFiles'),pickFolder:document.getElementById('pickFolder'),dropzone:document.getElementById('dropzone'),detailDialog:document.getElementById('detailDialog'),detailBody:document.getElementById('detailBody'),openFile:document.getElementById('openFile'),downloadFile:document.getElementById('downloadFile'),closeDetail:document.getElementById('closeDetail'),shareDialog:document.getElementById('shareDialog'),shareTarget:document.getElementById('shareTarget'),shareLink:document.getElementById('shareLink'),createShare:document.getElementById('createShare'),copyShare:document.getElementById('copyShare'),closeShare:document.getElementById('closeShare')};
    const fmt=new Intl.NumberFormat('zh-CN');
    const esc=(v)=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
    const bytes=(n)=>{if(n==null)return '-';const u=['B','KB','MB','GB','TB'];let v=Number(n),i=0;while(v>=1024&&i<u.length-1){v/=1024;i++}return v.toFixed(v>=100||i===0?0:1)+' '+u[i]};
    const time=(v)=>v?new Date(v).toLocaleString('zh-CN',{hour12:false}):'-';
    const setStatus=(t,k='')=>{e.status.textContent=t;e.status.className=k?'status '+k:'status'};
    const api=async(url,opt)=>{const r=await fetch(url,opt);const c=r.headers.get('content-type')||'';const d=c.includes('application/json')?await r.json():await r.text();if(!r.ok)throw new Error(typeof d==='string'?d:(d.error||r.statusText));return d};
    const fileUrl=(path,download)=>'/api/file?path='+encodeURIComponent(path)+(download?'&download=1':'');
    function crumbsRender(prefix){e.crumbs.innerHTML='';const root=document.createElement('button');root.textContent='root';root.onclick=()=>load('');e.crumbs.appendChild(root);const parts=prefix?prefix.replace(/\\\/$/,'').split('/'):[];let current='';for(const part of parts){const sep=document.createElement('span');sep.textContent='/';e.crumbs.appendChild(sep);current+=part+'/';const btn=document.createElement('button');btn.textContent=part;const target=current;btn.onclick=()=>load(target);e.crumbs.appendChild(btn)}}
    async function session(){const data=await api('/api/session');state.session=data;e.who.textContent='已登录：'+data.email}
    async function load(prefix=state.prefix){state.prefix=prefix;crumbsRender(prefix);e.pathView.textContent=prefix?'/'+prefix:'/';setStatus('正在加载目录…');try{const data=await api('/api/list?prefix='+encodeURIComponent(prefix));renderRows(data);e.folderCount.textContent=fmt.format(data.folders.length);e.fileCount.textContent=fmt.format(data.files.length);setStatus('已加载 '+fmt.format(data.folders.length+data.files.length)+' 个项目','success')}catch(err){setStatus(err.message||'目录加载失败','error')}}
    function renderRows(data){if(!data.folders.length&&!data.files.length){e.rows.innerHTML='<tr><td colspan="6" class="muted">当前目录为空，可以直接上传文件或文件夹。</td></tr>';return}const html=[];for(const folder of data.folders){html.push('<tr class="row" data-kind="folder" data-path="'+esc(folder.path)+'"><td class="name">📁 '+esc(folder.name)+'</td><td>文件夹</td><td>-</td><td>-</td><td>-</td><td class="muted">点击进入 / 右键分享</td></tr>')}for(const file of data.files){html.push('<tr class="row" data-kind="file" data-path="'+esc(file.path)+'"><td class="name">📄 '+esc(file.name)+'</td><td>文件</td><td>'+bytes(file.size)+'</td><td>'+esc(time(file.uploaded))+'</td><td>'+esc(file.contentType||'-')+'</td><td class="muted">点击详情 / 右键分享</td></tr>')}e.rows.innerHTML=html.join('');for(const row of e.rows.querySelectorAll("tr[data-kind='folder']")){row.onclick=()=>load(row.dataset.path)}for(const row of e.rows.querySelectorAll("tr[data-kind='file']")){row.onclick=()=>detail(row.dataset.path)}}
    async function detail(path){state.detail={path};const data=await api('/api/object?path='+encodeURIComponent(path));const items=[['路径',data.path],['名称',data.name],['类型',data.kind==='folder'?'文件夹':'文件'],['大小',data.size==null?'-':bytes(data.size)],['上传时间',time(data.uploaded)],['MIME',data.contentType||'-'],['ETag',data.etag||'-']];e.detailBody.innerHTML=items.map((item)=>'<div class="info"><div class="muted">'+esc(item[0])+'</div><div class="mono">'+esc(String(item[1]))+'</div></div>').join('');const disabled=data.kind!=='file';e.openFile.disabled=disabled;e.downloadFile.disabled=disabled;e.detailDialog.showModal()}
    async function upload(files){if(!files.length)return;const fd=new FormData();fd.append('basePath',state.prefix);for(const file of files){fd.append('files',file,file.name);fd.append('paths',file.webkitRelativePath||file.name)}setStatus('正在上传 '+fmt.format(files.length)+' 个文件…');try{const out=await api('/api/upload',{method:'POST',body:fd});setStatus('上传完成：'+fmt.format(out.uploaded)+' 个文件','success');await load(state.prefix)}catch(err){setStatus(err.message||'上传失败','error')}}
    function openShare(target){state.share=target;e.shareTarget.textContent='目标：'+target.path;e.shareLink.value='';e.shareDialog.showModal()}
    async function createShareLink(){if(!state.share)return;const out=await api('/api/share',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(state.share)});e.shareLink.value=out.url;setStatus('分享链接已生成','success')}
    e.refresh.onclick=()=>load(state.prefix);e.closeDetail.onclick=()=>e.detailDialog.close();e.closeShare.onclick=()=>e.shareDialog.close();e.openFile.onclick=()=>state.detail&&window.open(fileUrl(state.detail.path,false),'_blank','noopener');e.downloadFile.onclick=()=>state.detail&&window.open(fileUrl(state.detail.path,true),'_blank','noopener');e.createShare.onclick=()=>createShareLink().catch(err=>setStatus(err.message||'生成分享失败','error'));e.copyShare.onclick=async()=>{if(!e.shareLink.value)return;await navigator.clipboard.writeText(e.shareLink.value);setStatus('分享链接已复制','success')};
    e.pickFiles.addEventListener('change',async()=>{const files=Array.from(e.pickFiles.files||[]);await upload(files);e.pickFiles.value=''});e.pickFolder.addEventListener('change',async()=>{const files=Array.from(e.pickFolder.files||[]);await upload(files);e.pickFolder.value='' });
    ['dragenter','dragover'].forEach((name)=>e.dropzone.addEventListener(name,(ev)=>{ev.preventDefault();e.dropzone.classList.add('active')}));['dragleave','drop'].forEach((name)=>e.dropzone.addEventListener(name,(ev)=>{ev.preventDefault();e.dropzone.classList.remove('active')}));e.dropzone.addEventListener('drop',async(ev)=>{const files=[];for(const item of (ev.dataTransfer?.items||[])){if(item.kind!=='file')continue;const file=item.getAsFile();if(file)files.push(file)}await upload(files)});
    e.rows.addEventListener('contextmenu',(ev)=>{const row=ev.target.closest('tr[data-path]');if(!row)return;ev.preventDefault();openShare({path:row.dataset.path,kind:row.dataset.kind})});
    Promise.resolve().then(session).then(()=>load('')).catch(err=>setStatus(err.message||'初始化失败','error'));
  </script></body></html>`;
}

export function renderShareHtml(options: ShareOptions): string {
  const appName = safe(options.appName);
  const shareCode = safe(options.shareCode);
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1" /><title>${appName} 分享</title><style>${styles}</style></head><body>
  <div class="page">
    <section class="hero"><div><h1>${appName} 分享</h1><p>浏览公开分享的文件或文件夹，并按需下载。</p></div><div class="actions"><a class="btn" href="/app">进入后台</a></div></section>
    <section class="card" style="margin-top:16px"><div class="card-head"><div><div class="muted">分享编号</div><div class="mono">${shareCode}</div><div class="crumbs" id="crumbs"></div></div><div class="actions"><button class="btn" id="refresh">刷新</button><button class="btn primary" id="downloadSelected" disabled>下载选中</button></div></div><div class="card-body"><div class="status" id="status"></div><div class="stack" id="summary"></div><div class="table"><table><thead><tr><th></th><th>名称</th><th>类型</th><th>大小</th><th>更新时间</th><th>操作</th></tr></thead><tbody id="rows"></tbody></table></div></div></section>
  </div>
  <script>
    const state={code:${JSON.stringify(shareCode)},sub:'',selected:new Set(),mode:'folder'};
    const e={crumbs:document.getElementById('crumbs'),refresh:document.getElementById('refresh'),downloadSelected:document.getElementById('downloadSelected'),status:document.getElementById('status'),summary:document.getElementById('summary'),rows:document.getElementById('rows')};
    const esc=(v)=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
    const bytes=(n)=>{if(n==null)return '-';const u=['B','KB','MB','GB','TB'];let v=Number(n),i=0;while(v>=1024&&i<u.length-1){v/=1024;i++}return v.toFixed(v>=100||i===0?0:1)+' '+u[i]};
    const time=(v)=>v?new Date(v).toLocaleString('zh-CN',{hour12:false}):'-';
    const setStatus=(t,k='')=>{e.status.textContent=t;e.status.className=k?'status '+k:'status'};
    const api=async(url)=>{const r=await fetch(url);const c=r.headers.get('content-type')||'';const d=c.includes('application/json')?await r.json():await r.text();if(!r.ok)throw new Error(typeof d==='string'?d:(d.error||r.statusText));return d};
    const sharedUrl=(path,download)=>path?('/s/'+state.code+'/file?path='+encodeURIComponent(path)+(download?'&download=1':'')):('/s/'+state.code+'/file'+(download?'?download=1':''));
    function updatePick(){e.downloadSelected.disabled=state.mode!=='folder'||state.selected.size===0}
    function crumbsRender(){e.crumbs.innerHTML='';const root=document.createElement('button');root.textContent='分享根目录';root.onclick=()=>load('');e.crumbs.appendChild(root);const parts=state.sub?state.sub.replace(/\\\/$/,'').split('/'):[];let current='';for(const part of parts){const sep=document.createElement('span');sep.textContent='/';e.crumbs.appendChild(sep);current+=part+'/';const btn=document.createElement('button');btn.textContent=part;const target=current;btn.onclick=()=>load(target);e.crumbs.appendChild(btn)}}
    function summaryRender(data){const list=[['类型',data.kind==='file'?'文件分享':'文件夹分享'],['原始路径',data.rootPath],['当前目录',data.currentPrefix||data.rootPath],['项目数量',String((data.folders?.length||0)+(data.files?.length||0))]];e.summary.innerHTML=list.map((item)=>'<div class="info"><div class="muted">'+esc(item[0])+'</div><div class="mono">'+esc(String(item[1]))+'</div></div>').join('')}
    function rowsRender(data){state.selected.clear();updatePick();if(data.kind==='file'){state.mode='file';e.rows.innerHTML='<tr><td></td><td class="name">📄 '+esc(data.file.name)+'</td><td>文件</td><td>'+bytes(data.file.size)+'</td><td>'+esc(time(data.file.uploaded))+'</td><td><div class="actions"><a class="btn" href="'+sharedUrl('',false)+'" target="_blank" rel="noopener">在线打开</a><a class="btn primary" href="'+sharedUrl('',true)+'">下载</a></div></td></tr>';return}state.mode='folder';if(!data.folders.length&&!data.files.length){e.rows.innerHTML='<tr><td colspan="6" class="muted">这个分享目录当前没有可展示的文件。</td></tr>';return}const html=[];for(const folder of data.folders){html.push('<tr class="row" data-folder="'+esc(folder.subpath)+'"><td></td><td class="name">📁 '+esc(folder.name)+'</td><td>文件夹</td><td>-</td><td>-</td><td class="muted">点击进入</td></tr>')}for(const file of data.files){html.push('<tr data-file="'+esc(file.subpath)+'"><td><input type="checkbox" data-pick="'+esc(file.subpath)+'" /></td><td class="name">📄 '+esc(file.name)+'</td><td>文件</td><td>'+bytes(file.size)+'</td><td>'+esc(time(file.uploaded))+'</td><td><div class="actions"><a class="btn" href="'+sharedUrl(file.subpath,false)+'" target="_blank" rel="noopener">在线打开</a><a class="btn primary" href="'+sharedUrl(file.subpath,true)+'">下载</a></div></td></tr>')}e.rows.innerHTML=html.join('');for(const row of e.rows.querySelectorAll('tr[data-folder]')){row.onclick=()=>load(row.dataset.folder)}for(const box of e.rows.querySelectorAll('input[data-pick]')){box.addEventListener('change',()=>{const v=box.dataset.pick;if(!v)return;if(box.checked)state.selected.add(v);else state.selected.delete(v);updatePick()})}}
    async function load(sub=state.sub){state.sub=sub;crumbsRender();setStatus('正在加载分享内容…');try{const data=await api('/share-api/'+state.code+'?sub='+encodeURIComponent(sub));summaryRender(data);rowsRender(data);setStatus('分享内容已更新','success')}catch(err){setStatus(err.message||'分享加载失败','error')}}
    e.refresh.onclick=()=>load(state.sub);e.downloadSelected.onclick=()=>{for(const path of state.selected){window.open(sharedUrl(path,true),'_blank','noopener')}};load('');
  </script></body></html>`;
}
